Adding Buttons
MaksymKalennyk/telegramBotApplication pull request #6
Opened 2023-10-09 19:25 UTC by Qwertua

2023-10-09 19:29 UTC, MaksymKalennyk requested changes

2023-10-09 19:29 UTC, MaksymKalennyk commented on src/main/java/com/example/telegrambotapplication/bot/TelegramBot.java
> +        return markup;
пропуск нужен

2023-10-09 19:29 UTC, MaksymKalennyk commented on src/main/java/com/example/telegrambotapplication/bot/TelegramBot.java
> +    private ReplyKeyboardMarkup Menu(){
название метода с маленькой

2023-10-09 19:29 UTC, MaksymKalennyk commented on src/main/java/com/example/telegrambotapplication/bot/TelegramBot.java
> +
лишние пропуски

2023-10-10 19:13 UTC, MaksymKalennyk requested changes

2023-10-10 19:13 UTC, MaksymKalennyk commented on src/main/java/com/example/telegrambotapplication/bot/TelegramBot.java
> +    private ReplyKeyboardMarkup menu(){
нужен пропуск

2023-10-10 19:16 UTC, MaksymKalennyk approved these changes

2023-10-11 17:48 UTC, Miro60cent commented
nice

2023-10-14 21:01 UTC, merged